name: test_env_predict_sahel_rainfall
channels:
  - conda-forge
dependencies:
  - python=3.7
  ############## These will have to be adjusted to your specific project
  - numpy
  - scipy
  - xarray
  - tensorflow
  ##############
  - pytest
  - pip:
    - codecov
    - pytest-cov
    - coverage[toml]
